CREATE DATABASE [Library]
GO

USE Library;

CREATE TABLE Reader(
Id int IDENTITY NOT NULL PRIMARY KEY,
FirstName VARCHAR(75) NOT NULL,
LastName VARCHAR(75) NOT NULL,
Phone Varchar(50) NOT NULL UNIQUE);

CREATE TABLE Book(
Id INT IDENTITY NOT NULL PRIMARY KEY,
Author VARCHAR(200) NOT NULL,
Title VARCHAR(200) NOT NULL,
Quantity INT NOT NULL);

CREATE TABLE LibraryCard(
Id INT IDENTITY NOT NULL PRIMARY KEY,
ReaderId INT FOREIGN KEY REFERENCES Reader(Id) NOT NULL,
BookId INT FOREIGN KEY REFERENCES Book(Id) NOT NULL,
GivenDate DATETIME NOT NULL,
ScheduleReturnDate DATETIME NOT NULL,
ReturnDate DATETIME NULL);